// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#include "../ui.h"

void ui_Screenadd_screen_init(void)
{
    ui_Screenadd = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenadd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView = lv_tabview_create(ui_Screenadd, LV_DIR_LEFT, 100);
    lv_obj_set_width(ui_TabView, 800);
    lv_obj_set_height(ui_TabView, 480);
    lv_obj_set_x(ui_TabView, 0);
    lv_obj_set_y(ui_TabView, -1);
    lv_obj_clear_flag(ui_TabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RTabPage = lv_tabview_add_tab(ui_TabView, "Resistor");

    ui_RPanel = lv_obj_create(ui_RTabPage);
    lv_obj_set_width(ui_RPanel, 650);
    lv_obj_set_height(ui_RPanel, 150);
    lv_obj_clear_flag(ui_RPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RvalueTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RvalueTA, 120);
    lv_obj_set_height(ui_RvalueTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RvalueTA, lv_pct(5));
    lv_obj_set_y(ui_RvalueTA, lv_pct(10));
    if("1234567890.rk" == "") lv_textarea_set_accepted_chars(ui_RvalueTA, NULL);
    else lv_textarea_set_accepted_chars(ui_RvalueTA, "1234567890.rk");
    lv_textarea_set_max_length(ui_RvalueTA, 16);
    lv_textarea_set_placeholder_text(ui_RvalueTA, "value");

    ui_RpackageTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RpackageTA, 120);
    lv_obj_set_height(ui_RpackageTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpackageTA, lv_pct(5));
    lv_obj_set_y(ui_RpackageTA, lv_pct(60));
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_RpackageTA, NULL);
    else lv_textarea_set_accepted_chars(ui_RpackageTA, "1234567890");
    lv_textarea_set_max_length(ui_RpackageTA, 16);
    lv_textarea_set_placeholder_text(ui_RpackageTA, "package");

    ui_RratedTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RratedTA, 120);
    lv_obj_set_height(ui_RratedTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RratedTA, lv_pct(30));
    lv_obj_set_y(ui_RratedTA, lv_pct(10));
    if("1234567890.mkw" == "") lv_textarea_set_accepted_chars(ui_RratedTA, NULL);
    else lv_textarea_set_accepted_chars(ui_RratedTA, "1234567890.mkw");
    lv_textarea_set_max_length(ui_RratedTA, 16);
    lv_textarea_set_placeholder_text(ui_RratedTA, "power");

    ui_RtoleranceTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RtoleranceTA, 120);
    lv_obj_set_height(ui_RtoleranceTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RtoleranceTA, lv_pct(30));
    lv_obj_set_y(ui_RtoleranceTA, lv_pct(60));
    if("1234567890.%" == "") lv_textarea_set_accepted_chars(ui_RtoleranceTA, NULL);
    else lv_textarea_set_accepted_chars(ui_RtoleranceTA, "1234567890.%");
    lv_textarea_set_max_length(ui_RtoleranceTA, 16);
    lv_textarea_set_placeholder_text(ui_RtoleranceTA, "accuracy");

    ui_RotherTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RotherTA, 120);
    lv_obj_set_height(ui_RotherTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotherTA, lv_pct(55));
    lv_obj_set_y(ui_RotherTA, lv_pct(10));
    lv_textarea_set_max_length(ui_RotherTA, 16);
    lv_textarea_set_placeholder_text(ui_RotherTA, "other");

    ui_RquantityTA = lv_textarea_create(ui_RPanel);
    lv_obj_set_width(ui_RquantityTA, 120);
    lv_obj_set_height(ui_RquantityTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RquantityTA, lv_pct(55));
    lv_obj_set_y(ui_RquantityTA, lv_pct(60));
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_RquantityTA, NULL);
    else lv_textarea_set_accepted_chars(ui_RquantityTA, "1234567890");
    lv_textarea_set_max_length(ui_RquantityTA, 16);
    lv_textarea_set_placeholder_text(ui_RquantityTA, "quantity");

    ui_CTabPage = lv_tabview_add_tab(ui_TabView, "Capacitor");

    ui_CPanel = lv_obj_create(ui_CTabPage);
    lv_obj_set_width(ui_CPanel, 650);
    lv_obj_set_height(ui_CPanel, 150);
    lv_obj_clear_flag(ui_CPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CvalueTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CvalueTA, 120);
    lv_obj_set_height(ui_CvalueTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CvalueTA, lv_pct(5));
    lv_obj_set_y(ui_CvalueTA, lv_pct(10));
    if("1234567890.fmunp" == "") lv_textarea_set_accepted_chars(ui_CvalueTA, NULL);
    else lv_textarea_set_accepted_chars(ui_CvalueTA, "1234567890.fmunp");
    lv_textarea_set_max_length(ui_CvalueTA, 16);
    lv_textarea_set_placeholder_text(ui_CvalueTA, "value");

    ui_CpackageTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CpackageTA, 120);
    lv_obj_set_height(ui_CpackageTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CpackageTA, lv_pct(5));
    lv_obj_set_y(ui_CpackageTA, lv_pct(60));
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_CpackageTA, NULL);
    else lv_textarea_set_accepted_chars(ui_CpackageTA, "1234567890");
    lv_textarea_set_max_length(ui_CpackageTA, 16);
    lv_textarea_set_placeholder_text(ui_CpackageTA, "package");

    ui_CratedTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CratedTA, 120);
    lv_obj_set_height(ui_CratedTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CratedTA, lv_pct(30));
    lv_obj_set_y(ui_CratedTA, lv_pct(10));
    if("1234567890.mua" == "") lv_textarea_set_accepted_chars(ui_CratedTA, NULL);
    else lv_textarea_set_accepted_chars(ui_CratedTA, "1234567890.mua");
    lv_textarea_set_max_length(ui_CratedTA, 16);
    lv_textarea_set_placeholder_text(ui_CratedTA, "current");

    ui_CtoleranceTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CtoleranceTA, 120);
    lv_obj_set_height(ui_CtoleranceTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CtoleranceTA, lv_pct(30));
    lv_obj_set_y(ui_CtoleranceTA, lv_pct(60));
    if("1234567890.%" == "") lv_textarea_set_accepted_chars(ui_CtoleranceTA, NULL);
    else lv_textarea_set_accepted_chars(ui_CtoleranceTA, "1234567890.%");
    lv_textarea_set_max_length(ui_CtoleranceTA, 16);
    lv_textarea_set_placeholder_text(ui_CtoleranceTA, "accuracy");

    ui_CotherTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CotherTA, 120);
    lv_obj_set_height(ui_CotherTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CotherTA, lv_pct(55));
    lv_obj_set_y(ui_CotherTA, lv_pct(10));
    lv_textarea_set_max_length(ui_CotherTA, 16);
    lv_textarea_set_placeholder_text(ui_CotherTA, "other");

    ui_CquantityTA = lv_textarea_create(ui_CPanel);
    lv_obj_set_width(ui_CquantityTA, 120);
    lv_obj_set_height(ui_CquantityTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CquantityTA, lv_pct(55));
    lv_obj_set_y(ui_CquantityTA, lv_pct(60));
    if("01234567890" == "") lv_textarea_set_accepted_chars(ui_CquantityTA, NULL);
    else lv_textarea_set_accepted_chars(ui_CquantityTA, "01234567890");
    lv_textarea_set_max_length(ui_CquantityTA, 16);
    lv_textarea_set_placeholder_text(ui_CquantityTA, "quantity");

    ui_ITabPage = lv_tabview_add_tab(ui_TabView, "Inductor");

    ui_IPanel = lv_obj_create(ui_ITabPage);
    lv_obj_set_width(ui_IPanel, 650);
    lv_obj_set_height(ui_IPanel, 150);
    lv_obj_clear_flag(ui_IPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IvalueTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_IvalueTA, 120);
    lv_obj_set_height(ui_IvalueTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IvalueTA, lv_pct(5));
    lv_obj_set_y(ui_IvalueTA, lv_pct(10));
    if("1234567890.umh" == "") lv_textarea_set_accepted_chars(ui_IvalueTA, NULL);
    else lv_textarea_set_accepted_chars(ui_IvalueTA, "1234567890.umh");
    lv_textarea_set_max_length(ui_IvalueTA, 16);
    lv_textarea_set_placeholder_text(ui_IvalueTA, "value");

    ui_IpackageTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_IpackageTA, 120);
    lv_obj_set_height(ui_IpackageTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IpackageTA, lv_pct(5));
    lv_obj_set_y(ui_IpackageTA, lv_pct(60));
    lv_textarea_set_max_length(ui_IpackageTA, 16);
    lv_textarea_set_placeholder_text(ui_IpackageTA, "package");

    ui_IratedTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_IratedTA, 120);
    lv_obj_set_height(ui_IratedTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IratedTA, lv_pct(30));
    lv_obj_set_y(ui_IratedTA, lv_pct(10));
    if("1234567890.ma" == "") lv_textarea_set_accepted_chars(ui_IratedTA, NULL);
    else lv_textarea_set_accepted_chars(ui_IratedTA, "1234567890.ma");
    lv_textarea_set_max_length(ui_IratedTA, 16);
    lv_textarea_set_placeholder_text(ui_IratedTA, "current");

    ui_ItoleranceTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_ItoleranceTA, 120);
    lv_obj_set_height(ui_ItoleranceTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ItoleranceTA, lv_pct(30));
    lv_obj_set_y(ui_ItoleranceTA, lv_pct(60));
    if("1234567890.%" == "") lv_textarea_set_accepted_chars(ui_ItoleranceTA, NULL);
    else lv_textarea_set_accepted_chars(ui_ItoleranceTA, "1234567890.%");
    lv_textarea_set_max_length(ui_ItoleranceTA, 16);
    lv_textarea_set_placeholder_text(ui_ItoleranceTA, "accuracy");

    ui_IotherTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_IotherTA, 120);
    lv_obj_set_height(ui_IotherTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IotherTA, lv_pct(55));
    lv_obj_set_y(ui_IotherTA, lv_pct(10));
    lv_textarea_set_max_length(ui_IotherTA, 16);
    lv_textarea_set_placeholder_text(ui_IotherTA, "other");

    ui_IquantityTA = lv_textarea_create(ui_IPanel);
    lv_obj_set_width(ui_IquantityTA, 120);
    lv_obj_set_height(ui_IquantityTA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IquantityTA, lv_pct(55));
    lv_obj_set_y(ui_IquantityTA, lv_pct(60));
    if("01234567890" == "") lv_textarea_set_accepted_chars(ui_IquantityTA, NULL);
    else lv_textarea_set_accepted_chars(ui_IquantityTA, "01234567890");
    lv_textarea_set_max_length(ui_IquantityTA, 16);
    lv_textarea_set_placeholder_text(ui_IquantityTA, "quantity");

    ui_addButton = lv_btn_create(ui_Screenadd);
    lv_obj_set_width(ui_addButton, 108);
    lv_obj_set_height(ui_addButton, 60);
    lv_obj_set_x(ui_addButton, 280);
    lv_obj_set_y(ui_addButton, -150);
    lv_obj_set_align(ui_addButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_addButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_addButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_addButton, lv_color_hex(0x52C273), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnLabel = lv_label_create(ui_addButton);
    lv_obj_set_width(ui_btnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnLabel, "Add");

    ui_addKeyboard = lv_keyboard_create(ui_Screenadd);
    lv_keyboard_set_mode(ui_addKeyboard, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_addKeyboard, 680);
    lv_obj_set_height(ui_addKeyboard, 240);
    lv_obj_set_x(ui_addKeyboard, 50);
    lv_obj_set_y(ui_addKeyboard, 0);
    lv_obj_set_align(ui_addKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_addKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_RvalueTA, ui_event_RvalueTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RpackageTA, ui_event_RpackageTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RratedTA, ui_event_RratedTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RtoleranceTA, ui_event_RtoleranceTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RotherTA, ui_event_RotherTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RquantityTA, ui_event_RquantityTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RTabPage, ui_event_RTabPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CvalueTA, ui_event_CvalueTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CpackageTA, ui_event_CpackageTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CratedTA, ui_event_CratedTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CtoleranceTA, ui_event_CtoleranceTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CotherTA, ui_event_CotherTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CquantityTA, ui_event_CquantityTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CTabPage, ui_event_CTabPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IvalueTA, ui_event_IvalueTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IpackageTA, ui_event_IpackageTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IratedTA, ui_event_IratedTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ItoleranceTA, ui_event_ItoleranceTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IotherTA, ui_event_IotherTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IquantityTA, ui_event_IquantityTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ITabPage, ui_event_ITabPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addButton, ui_event_addButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addKeyboard, ui_event_addKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screenadd, ui_event_Screenadd, LV_EVENT_ALL, NULL);

}
