// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#include "../ui.h"

void ui_Screenfind_screen_init(void)
{
    ui_Screenfind = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenfind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewfind = lv_tabview_create(ui_Screenfind, LV_DIR_LEFT, 100);
    lv_obj_set_width(ui_TabViewfind, 800);
    lv_obj_set_height(ui_TabViewfind, 480);
    lv_obj_set_x(ui_TabViewfind, 0);
    lv_obj_set_y(ui_TabViewfind, -1);
    lv_obj_clear_flag(ui_TabViewfind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RTabPagefind = lv_tabview_add_tab(ui_TabViewfind, "Resistor");

    ui_RPanel1 = lv_obj_create(ui_RTabPagefind);
    lv_obj_set_width(ui_RPanel1, 650);
    lv_obj_set_height(ui_RPanel1, 120);
    lv_obj_clear_flag(ui_RPanel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RvalueTA1 = lv_textarea_create(ui_RPanel1);
    lv_obj_set_width(ui_RvalueTA1, 120);
    lv_obj_set_height(ui_RvalueTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RvalueTA1, lv_pct(5));
    lv_obj_set_y(ui_RvalueTA1, lv_pct(10));
    if("1234567890.rkK" == "") lv_textarea_set_accepted_chars(ui_RvalueTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_RvalueTA1, "1234567890.rkK");
    lv_textarea_set_max_length(ui_RvalueTA1, 8);
    lv_textarea_set_placeholder_text(ui_RvalueTA1, "value");

    ui_RpackageTA1 = lv_textarea_create(ui_RPanel1);
    lv_obj_set_width(ui_RpackageTA1, 120);
    lv_obj_set_height(ui_RpackageTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpackageTA1, lv_pct(5));
    lv_obj_set_y(ui_RpackageTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_RpackageTA1, "package");

    ui_RratedTA1 = lv_textarea_create(ui_RPanel1);
    lv_obj_set_width(ui_RratedTA1, 120);
    lv_obj_set_height(ui_RratedTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RratedTA1, lv_pct(30));
    lv_obj_set_y(ui_RratedTA1, lv_pct(10));
    if("1234567890.mkwW" == "") lv_textarea_set_accepted_chars(ui_RratedTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_RratedTA1, "1234567890.mkwW");
    lv_textarea_set_max_length(ui_RratedTA1, 8);
    lv_textarea_set_placeholder_text(ui_RratedTA1, "power");

    ui_RtoleranceTA1 = lv_textarea_create(ui_RPanel1);
    lv_obj_set_width(ui_RtoleranceTA1, 120);
    lv_obj_set_height(ui_RtoleranceTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RtoleranceTA1, lv_pct(30));
    lv_obj_set_y(ui_RtoleranceTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_RtoleranceTA1, "accuracy");

    ui_RotherTA1 = lv_textarea_create(ui_RPanel1);
    lv_obj_set_width(ui_RotherTA1, 120);
    lv_obj_set_height(ui_RotherTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotherTA1, lv_pct(55));
    lv_obj_set_y(ui_RotherTA1, lv_pct(10));
    lv_textarea_set_max_length(ui_RotherTA1, 16);
    lv_textarea_set_placeholder_text(ui_RotherTA1, "other");

    ui_CTabPage1 = lv_tabview_add_tab(ui_TabViewfind, "Capacitor");

    ui_CPanel1 = lv_obj_create(ui_CTabPage1);
    lv_obj_set_width(ui_CPanel1, 650);
    lv_obj_set_height(ui_CPanel1, 120);
    lv_obj_clear_flag(ui_CPanel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CvalueTA1 = lv_textarea_create(ui_CPanel1);
    lv_obj_set_width(ui_CvalueTA1, 120);
    lv_obj_set_height(ui_CvalueTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CvalueTA1, lv_pct(5));
    lv_obj_set_y(ui_CvalueTA1, lv_pct(10));
    if("1234567890.pumf" == "") lv_textarea_set_accepted_chars(ui_CvalueTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_CvalueTA1, "1234567890.pumf");
    lv_textarea_set_max_length(ui_CvalueTA1, 8);
    lv_textarea_set_placeholder_text(ui_CvalueTA1, "value");

    ui_CpackageTA1 = lv_textarea_create(ui_CPanel1);
    lv_obj_set_width(ui_CpackageTA1, 120);
    lv_obj_set_height(ui_CpackageTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CpackageTA1, lv_pct(5));
    lv_obj_set_y(ui_CpackageTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_CpackageTA1, "package");

    ui_CratedTA1 = lv_textarea_create(ui_CPanel1);
    lv_obj_set_width(ui_CratedTA1, 120);
    lv_obj_set_height(ui_CratedTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CratedTA1, lv_pct(30));
    lv_obj_set_y(ui_CratedTA1, lv_pct(10));
    if("1234567890.mkw" == "") lv_textarea_set_accepted_chars(ui_CratedTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_CratedTA1, "1234567890.mkw");
    lv_textarea_set_max_length(ui_CratedTA1, 8);
    lv_textarea_set_placeholder_text(ui_CratedTA1, "current");

    ui_CtoleranceTA1 = lv_textarea_create(ui_CPanel1);
    lv_obj_set_width(ui_CtoleranceTA1, 120);
    lv_obj_set_height(ui_CtoleranceTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CtoleranceTA1, lv_pct(30));
    lv_obj_set_y(ui_CtoleranceTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_CtoleranceTA1, "accuracy");

    ui_CotherTA1 = lv_textarea_create(ui_CPanel1);
    lv_obj_set_width(ui_CotherTA1, 120);
    lv_obj_set_height(ui_CotherTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CotherTA1, lv_pct(55));
    lv_obj_set_y(ui_CotherTA1, lv_pct(10));
    lv_textarea_set_max_length(ui_CotherTA1, 16);
    lv_textarea_set_placeholder_text(ui_CotherTA1, "other");

    ui_ITabPage1 = lv_tabview_add_tab(ui_TabViewfind, "Inductor");

    ui_IPanel1 = lv_obj_create(ui_ITabPage1);
    lv_obj_set_width(ui_IPanel1, 650);
    lv_obj_set_height(ui_IPanel1, 120);
    lv_obj_clear_flag(ui_IPanel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IvalueTA1 = lv_textarea_create(ui_IPanel1);
    lv_obj_set_width(ui_IvalueTA1, 120);
    lv_obj_set_height(ui_IvalueTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IvalueTA1, lv_pct(5));
    lv_obj_set_y(ui_IvalueTA1, lv_pct(10));
    if("1234567890.umh" == "") lv_textarea_set_accepted_chars(ui_IvalueTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_IvalueTA1, "1234567890.umh");
    lv_textarea_set_max_length(ui_IvalueTA1, 8);
    lv_textarea_set_placeholder_text(ui_IvalueTA1, "value");

    ui_IpackageTA1 = lv_textarea_create(ui_IPanel1);
    lv_obj_set_width(ui_IpackageTA1, 120);
    lv_obj_set_height(ui_IpackageTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IpackageTA1, lv_pct(5));
    lv_obj_set_y(ui_IpackageTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_IpackageTA1, "package");

    ui_IratedTA1 = lv_textarea_create(ui_IPanel1);
    lv_obj_set_width(ui_IratedTA1, 120);
    lv_obj_set_height(ui_IratedTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IratedTA1, lv_pct(30));
    lv_obj_set_y(ui_IratedTA1, lv_pct(10));
    if("1234567890.ma" == "") lv_textarea_set_accepted_chars(ui_IratedTA1, NULL);
    else lv_textarea_set_accepted_chars(ui_IratedTA1, "1234567890.ma");
    lv_textarea_set_max_length(ui_IratedTA1, 8);
    lv_textarea_set_placeholder_text(ui_IratedTA1, "current");

    ui_ItoleranceTA1 = lv_textarea_create(ui_IPanel1);
    lv_obj_set_width(ui_ItoleranceTA1, 120);
    lv_obj_set_height(ui_ItoleranceTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ItoleranceTA1, lv_pct(30));
    lv_obj_set_y(ui_ItoleranceTA1, lv_pct(60));
    lv_textarea_set_placeholder_text(ui_ItoleranceTA1, "accuracy");

    ui_IotherTA1 = lv_textarea_create(ui_IPanel1);
    lv_obj_set_width(ui_IotherTA1, 120);
    lv_obj_set_height(ui_IotherTA1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IotherTA1, lv_pct(55));
    lv_obj_set_y(ui_IotherTA1, lv_pct(10));
    lv_textarea_set_max_length(ui_IotherTA1, 16);
    lv_textarea_set_placeholder_text(ui_IotherTA1, "other");

    ui_refreshLabel = lv_label_create(ui_Screenfind);
    lv_obj_set_width(ui_refreshLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refreshLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refreshLabel, -78);
    lv_obj_set_y(ui_refreshLabel, -82);
    lv_obj_set_align(ui_refreshLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_refreshLabel, "List:  KEY-----INFO--------------------------------------------QUANTITY");

    ui_refreshPanel = lv_obj_create(ui_Screenfind);
    lv_obj_set_width(ui_refreshPanel, 650);
    lv_obj_set_height(ui_refreshPanel, 290);
    lv_obj_set_x(ui_refreshPanel, -30);
    lv_obj_set_y(ui_refreshPanel, 80);
    lv_obj_set_align(ui_refreshPanel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_refreshPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_refreshPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_refreshPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_refreshPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_refreshPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_refreshPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ListPanel = ui_List_create(ui_refreshPanel);
    lv_obj_set_x(ui_ListPanel, 0);
    lv_obj_set_y(ui_ListPanel, 0);

    ui_refreshBTN = lv_btn_create(ui_Screenfind);
    lv_obj_set_width(ui_refreshBTN, 115);
    lv_obj_set_height(ui_refreshBTN, 60);
    lv_obj_set_x(ui_refreshBTN, 280);
    lv_obj_set_y(ui_refreshBTN, -160);
    lv_obj_set_align(ui_refreshBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_refreshBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_refreshBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_refreshBTN, lv_color_hex(0x41AEA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_refreshBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_refreshBTN);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Refresh list");

    ui_findKeyboard = lv_keyboard_create(ui_Screenfind);
    lv_keyboard_set_mode(ui_findKeyboard, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_findKeyboard, 680);
    lv_obj_set_height(ui_findKeyboard, 240);
    lv_obj_set_x(ui_findKeyboard, 50);
    lv_obj_set_y(ui_findKeyboard, 0);
    lv_obj_set_align(ui_findKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_findKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_RvalueTA1, ui_event_RvalueTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RpackageTA1, ui_event_RpackageTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RratedTA1, ui_event_RratedTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RtoleranceTA1, ui_event_RtoleranceTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RotherTA1, ui_event_RotherTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RTabPagefind, ui_event_RTabPagefind, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CvalueTA1, ui_event_CvalueTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CpackageTA1, ui_event_CpackageTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CratedTA1, ui_event_CratedTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CtoleranceTA1, ui_event_CtoleranceTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CotherTA1, ui_event_CotherTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CTabPage1, ui_event_CTabPage1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IvalueTA1, ui_event_IvalueTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IpackageTA1, ui_event_IpackageTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IratedTA1, ui_event_IratedTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ItoleranceTA1, ui_event_ItoleranceTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IotherTA1, ui_event_IotherTA1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ITabPage1, ui_event_ITabPage1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_refreshBTN, ui_event_refreshBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_findKeyboard, ui_event_findKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screenfind, ui_event_Screenfind, LV_EVENT_ALL, NULL);

}
