// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#ifndef _ARTPIDEMO_UI_H
#define _ARTPIDEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void kbshow_Animation(lv_obj_t * TargetObject, int delay);
void kbback_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screenmain
void ui_Screenmain_screen_init(void);
void ui_event_Screenmain(lv_event_t * e);
extern lv_obj_t * ui_Screenmain;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Screenadd
void ui_Screenadd_screen_init(void);
void ui_event_Screenadd(lv_event_t * e);
extern lv_obj_t * ui_Screenadd;
extern lv_obj_t * ui_TabView;
void ui_event_RTabPage(lv_event_t * e);
extern lv_obj_t * ui_RTabPage;
extern lv_obj_t * ui_RPanel;
void ui_event_RvalueTA(lv_event_t * e);
extern lv_obj_t * ui_RvalueTA;
void ui_event_RpackageTA(lv_event_t * e);
extern lv_obj_t * ui_RpackageTA;
void ui_event_RratedTA(lv_event_t * e);
extern lv_obj_t * ui_RratedTA;
void ui_event_RtoleranceTA(lv_event_t * e);
extern lv_obj_t * ui_RtoleranceTA;
void ui_event_RotherTA(lv_event_t * e);
extern lv_obj_t * ui_RotherTA;
void ui_event_RquantityTA(lv_event_t * e);
extern lv_obj_t * ui_RquantityTA;
void ui_event_CTabPage(lv_event_t * e);
extern lv_obj_t * ui_CTabPage;
extern lv_obj_t * ui_CPanel;
void ui_event_CvalueTA(lv_event_t * e);
extern lv_obj_t * ui_CvalueTA;
void ui_event_CpackageTA(lv_event_t * e);
extern lv_obj_t * ui_CpackageTA;
void ui_event_CratedTA(lv_event_t * e);
extern lv_obj_t * ui_CratedTA;
void ui_event_CtoleranceTA(lv_event_t * e);
extern lv_obj_t * ui_CtoleranceTA;
void ui_event_CotherTA(lv_event_t * e);
extern lv_obj_t * ui_CotherTA;
void ui_event_CquantityTA(lv_event_t * e);
extern lv_obj_t * ui_CquantityTA;
void ui_event_ITabPage(lv_event_t * e);
extern lv_obj_t * ui_ITabPage;
extern lv_obj_t * ui_IPanel;
void ui_event_IvalueTA(lv_event_t * e);
extern lv_obj_t * ui_IvalueTA;
void ui_event_IpackageTA(lv_event_t * e);
extern lv_obj_t * ui_IpackageTA;
void ui_event_IratedTA(lv_event_t * e);
extern lv_obj_t * ui_IratedTA;
void ui_event_ItoleranceTA(lv_event_t * e);
extern lv_obj_t * ui_ItoleranceTA;
void ui_event_IotherTA(lv_event_t * e);
extern lv_obj_t * ui_IotherTA;
void ui_event_IquantityTA(lv_event_t * e);
extern lv_obj_t * ui_IquantityTA;
void ui_event_addButton(lv_event_t * e);
extern lv_obj_t * ui_addButton;
extern lv_obj_t * ui_btnLabel;
void ui_event_addKeyboard(lv_event_t * e);
extern lv_obj_t * ui_addKeyboard;
// CUSTOM VARIABLES

// SCREEN: ui_Screenfind
void ui_Screenfind_screen_init(void);
void ui_event_Screenfind(lv_event_t * e);
extern lv_obj_t * ui_Screenfind;
extern lv_obj_t * ui_TabViewfind;
void ui_event_RTabPagefind(lv_event_t * e);
extern lv_obj_t * ui_RTabPagefind;
extern lv_obj_t * ui_RPanel1;
void ui_event_RvalueTA1(lv_event_t * e);
extern lv_obj_t * ui_RvalueTA1;
void ui_event_RpackageTA1(lv_event_t * e);
extern lv_obj_t * ui_RpackageTA1;
void ui_event_RratedTA1(lv_event_t * e);
extern lv_obj_t * ui_RratedTA1;
void ui_event_RtoleranceTA1(lv_event_t * e);
extern lv_obj_t * ui_RtoleranceTA1;
void ui_event_RotherTA1(lv_event_t * e);
extern lv_obj_t * ui_RotherTA1;
void ui_event_CTabPage1(lv_event_t * e);
extern lv_obj_t * ui_CTabPage1;
extern lv_obj_t * ui_CPanel1;
void ui_event_CvalueTA1(lv_event_t * e);
extern lv_obj_t * ui_CvalueTA1;
void ui_event_CpackageTA1(lv_event_t * e);
extern lv_obj_t * ui_CpackageTA1;
void ui_event_CratedTA1(lv_event_t * e);
extern lv_obj_t * ui_CratedTA1;
void ui_event_CtoleranceTA1(lv_event_t * e);
extern lv_obj_t * ui_CtoleranceTA1;
void ui_event_CotherTA1(lv_event_t * e);
extern lv_obj_t * ui_CotherTA1;
void ui_event_ITabPage1(lv_event_t * e);
extern lv_obj_t * ui_ITabPage1;
extern lv_obj_t * ui_IPanel1;
void ui_event_IvalueTA1(lv_event_t * e);
extern lv_obj_t * ui_IvalueTA1;
void ui_event_IpackageTA1(lv_event_t * e);
extern lv_obj_t * ui_IpackageTA1;
void ui_event_IratedTA1(lv_event_t * e);
extern lv_obj_t * ui_IratedTA1;
void ui_event_ItoleranceTA1(lv_event_t * e);
extern lv_obj_t * ui_ItoleranceTA1;
void ui_event_IotherTA1(lv_event_t * e);
extern lv_obj_t * ui_IotherTA1;
extern lv_obj_t * ui_refreshLabel;
extern lv_obj_t * ui_refreshPanel;
extern lv_obj_t * ui_ListPanel;
void ui_event_refreshBTN(lv_event_t * e);
extern lv_obj_t * ui_refreshBTN;
extern lv_obj_t * ui_Label3;
void ui_event_findKeyboard(lv_event_t * e);
extern lv_obj_t * ui_findKeyboard;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
