// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#include "stdlib.h"
#include "ui.h"
#include "database.h"
#include "pv_event.h"

extern rt_mq_t motor_mq;
extern rt_mq_t servo_mq;

void screen_touch_function(lv_event_t * e)
{
    rt_event_send(global_event, EVENT_TOUCH_SCREEN);
}

void ui_event_Textarea(lv_event_t *e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *keyboard = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_keyboard_set_textarea(keyboard, target);
    }
}

void event_finish_cb(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * msgbox = lv_event_get_current_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED){//changed
        if(lv_msgbox_get_active_btn(msgbox) == 0){
            rt_event_send(global_event, EVENT_PICK_FINNISH);    //取件完成，发送事件
            lv_msgbox_close(msgbox);
            rt_kprintf("finish\n");
        }
    }
}

void event_get_component_cb(lv_event_t *e){
    const char *key = NULL;
    const char *info = NULL;
    const char *numtext = NULL;
    uint32_t num = 0 , rest_num = 0;

    struct fdb_blob blob;
    component_info refreshinfo;

    screen_touch_function(e);
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_t *target = lv_event_get_target(e);
        lv_obj_t *list_panel = lv_obj_get_parent(target);
        lv_obj_t *key_label = lv_obj_get_child(list_panel, 0);
        lv_obj_t *info_label = lv_obj_get_child(list_panel, 1);
        lv_obj_t *restnum_label = lv_obj_get_child(list_panel, 2);
        lv_obj_t *add_switch = lv_obj_get_child(list_panel, 3);
        lv_obj_t *num_textarea = lv_obj_get_child(list_panel, 4);


        key = lv_label_get_text(key_label);
        info = lv_label_get_text(info_label);
        rest_num = atoi(lv_label_get_text(restnum_label));
        numtext = lv_textarea_get_text(num_textarea);

        if(numtext[0] == '\0'){                 //输入num为空
            lv_obj_t * warnmsgbox1 = lv_msgbox_create(NULL, "WARNING", "plaese enter the num", NULL, true);
            lv_obj_center(warnmsgbox1);
            return;
        }
        num = atoi(numtext);
        if((lv_obj_has_state(add_switch, LV_STATE_CHECKED) == false) && (num > rest_num)){      //取器件但是num大于剩余数量
            lv_obj_t * warnmsgbox2 = lv_msgbox_create(NULL, "WARNING", "quantity is not enough", NULL, true);
            lv_obj_center(warnmsgbox2);
            return;
        }

        strncpy(refreshinfo.para_info, info, sizeof(refreshinfo.para_info));
        refreshinfo.quantity = rest_num;
        if(lv_obj_has_state(add_switch, LV_STATE_CHECKED) == true){     //添加num_textarea中数量的器件
            refreshinfo.quantity += num;
            lv_label_set_text_fmt(restnum_label, "%ld",refreshinfo.quantity);
            fdb_kv_set_blob(&components_kv_db, key, fdb_blob_make(&blob, &refreshinfo, sizeof(component_info)));    //添加数量后修改信息

        }else {                     //取出num_textarea中数量的器件
            if(num == rest_num){             //器件全部取完 删除KV 删除列表元素
                fdb_kv_del(&components_kv_db, key);
                lv_obj_del_async(list_panel);
            }else {
                refreshinfo.quantity -= num;
                lv_label_set_text_fmt(restnum_label, "%ld",refreshinfo.quantity);
                fdb_kv_set_blob(&components_kv_db, key, fdb_blob_make(&blob, &refreshinfo, sizeof(component_info)));    //取出数量后修改信息
            }
        }
        //消息队列发送坐标
        rt_uint8_t pos = atoi(key)%12;
        rt_uint8_t level = atoi(key)/12;
        rt_mq_send(motor_mq, &pos, sizeof(pos));        //发送存储位置信息
        rt_mq_send(servo_mq, &level, sizeof(level));    //发送存储层数信息

        static const char * btns[] = {"Finish", ""};
        lv_obj_t * finish_msgbox = lv_msgbox_create(NULL, "INFO", "click the button when finished", btns, false);
        lv_obj_add_event_cb(finish_msgbox, event_finish_cb, LV_EVENT_VALUE_CHANGED, NULL);
        lv_obj_center(finish_msgbox);
    }
}


void addBTN_call_function(lv_event_t *e){
    // Your code here
    eCOMPONENTS_TYPE current_tab;
    current_tab = lv_tabview_get_tab_act(ui_TabView);   //判断添加器件类型

    cJSON *root = cJSON_CreateObject();
    const char *val;
    const char *package;
    const char *ratedval;
    const char *tolerance;
    const char *otherinfo;
    uint32_t quantity;

    if(current_tab == COMPONENTS_RESRISTOR){                    //电阻
        val = lv_textarea_get_text(ui_RvalueTA);
        package = lv_textarea_get_text(ui_RpackageTA);
        ratedval = lv_textarea_get_text(ui_RratedTA);
        tolerance = lv_textarea_get_text(ui_RtoleranceTA);
        otherinfo = lv_textarea_get_text(ui_RotherTA);
        quantity= atoi(lv_textarea_get_text(ui_RquantityTA));

        cJSON_AddStringToObject(root, "type", "Resistor");
    }else if(current_tab == COMPONENTS_CAPACITOR){              //电容
        val = lv_textarea_get_text(ui_CvalueTA);
        package = lv_textarea_get_text(ui_CpackageTA);
        ratedval = lv_textarea_get_text(ui_CratedTA);
        tolerance = lv_textarea_get_text(ui_CtoleranceTA);
        otherinfo = lv_textarea_get_text(ui_CotherTA);
        quantity= atoi(lv_textarea_get_text(ui_CquantityTA));

        cJSON_AddStringToObject(root, "type", "Capacitor");
    }else if(current_tab == COMPONENTS_INDUCTOR){               //电感
        val = lv_textarea_get_text(ui_IvalueTA);
        package = lv_textarea_get_text(ui_IpackageTA);
        ratedval = lv_textarea_get_text(ui_IratedTA);
        tolerance = lv_textarea_get_text(ui_ItoleranceTA);
        otherinfo = lv_textarea_get_text(ui_IotherTA);
        quantity= atoi(lv_textarea_get_text(ui_IquantityTA));

        cJSON_AddStringToObject(root, "type", "Indicator");
    }
    if(val[0]=='\0'||package[0]=='\0'||ratedval[0]=='\0'||tolerance[0]=='\0'||otherinfo[0]=='\0'){  //器件信息不完整
        static const char * btns[] = {""};
        lv_obj_t * msgbox = lv_msgbox_create(NULL, "INFO", "please complete the infomation", btns, true);
        lv_obj_center(msgbox);
        cJSON_Delete(root);
        return;
    }else {
        cJSON_AddStringToObject(root, "val", val);                                  //封装JSON为格式
        cJSON_AddStringToObject(root, "pkg", package);
        cJSON_AddStringToObject(root, "rated val", ratedval);
        cJSON_AddStringToObject(root, "accuracy", tolerance);
        cJSON_AddStringToObject(root, "other", otherinfo);
    }

    char *json_str = cJSON_PrintUnformatted(root);                                  //转化为字符串
    rt_kprintf("%s\n",json_str);
    components_add_kv(json_str, quantity);                                          //根据信息、数量添加至数据库
    //释放内存
    cJSON_free(json_str);
    cJSON_Delete(root);
}



void findBTN_call_function(lv_event_t *e){
     eCOMPONENTS_TYPE current_tab;
     current_tab = lv_tabview_get_tab_act(ui_TabViewfind);
     lv_obj_clean(ui_refreshPanel);

     filter_info_t filter = (filter_info_t)rt_malloc(sizeof(filter_info));
     if(filter == NULL){
         rt_kprintf("filter malloc failed\n");
         return;
     }
     memset(filter, 0, sizeof(filter_info));

     if(current_tab == COMPONENTS_RESRISTOR){
         strcpy(filter->type, "Resistor");
         filter->val = lv_textarea_get_text(ui_RvalueTA1);
         filter->package = lv_textarea_get_text(ui_RpackageTA1);
         filter->ratedval = lv_textarea_get_text(ui_RratedTA1);
         filter->tolerance = lv_textarea_get_text(ui_RtoleranceTA1);
         filter->otherinfo = lv_textarea_get_text(ui_RotherTA1);
     }else if(current_tab == COMPONENTS_CAPACITOR){
         strcpy(filter->type, "Capacitor");
         filter->val = lv_textarea_get_text(ui_CvalueTA1);
         filter->package = lv_textarea_get_text(ui_CpackageTA1);
         filter->ratedval = lv_textarea_get_text(ui_CratedTA1);
         filter->tolerance = lv_textarea_get_text(ui_CtoleranceTA1);
         filter->otherinfo = lv_textarea_get_text(ui_CotherTA1);
     }else if(current_tab == COMPONENTS_INDUCTOR){
         strcpy(filter->type, "Inductor");
         filter->val = lv_textarea_get_text(ui_IvalueTA1);
         filter->package = lv_textarea_get_text(ui_IpackageTA1);
         filter->ratedval = lv_textarea_get_text(ui_IratedTA1);
         filter->tolerance = lv_textarea_get_text(ui_ItoleranceTA1);
         filter->otherinfo = lv_textarea_get_text(ui_IotherTA1);
     }
     components_find_kv(filter);
     rt_free(filter);
}


extern lv_obj_t* ui_List_create(lv_obj_t * comp_parent);
//添加器件信息至列表
void add_component_to_list(const char *key, component_info_t info){
    lv_obj_t *list_panel = ui_List_create(ui_refreshPanel);

    lv_obj_t *key_label = lv_obj_get_child(list_panel, 0);
    lv_obj_t *info_label = lv_obj_get_child(list_panel, 1);
    lv_obj_t *quantity_label = lv_obj_get_child(list_panel, 2);
//    lv_obj_t *add_switch = lv_obj_get_child(list_panel, 3);
    lv_obj_t *numTA = lv_obj_get_child(list_panel, 4);
    lv_obj_t *btn = lv_obj_get_child(list_panel, 5);

    lv_label_set_text(key_label, key);
    lv_label_set_text(info_label, info->para_info);
    lv_label_set_text_fmt(quantity_label, "%ld",info->quantity);
    lv_obj_add_event_cb(numTA, ui_event_Textarea, LV_EVENT_CLICKED, ui_findKeyboard);
    lv_obj_add_event_cb(btn, event_get_component_cb, LV_EVENT_CLICKED, NULL);
}

//void touch_layer_init(){
//    lv_obj_t * touch_layer = lv_obj_create(lv_layer_top());
//    lv_obj_remove_style_all(touch_layer);
//    lv_obj_set_size(touch_layer, LV_PCT(100), LV_PCT(100));
//    lv_obj_clear_flag(touch_layer, LV_OBJ_FLAG_SCROLLABLE);
//    lv_obj_add_flag(touch_layer, LV_OBJ_FLAG_CLICKABLE);
//    lv_obj_add_flag(touch_layer, LV_OBJ_FLAG_EVENT_BUBBLE);
//    lv_obj_move_background(touch_layer); // 保证它在底部
//
//    lv_obj_add_event_cb(touch_layer, screen_touch_function, LV_EVENT_PRESSED, NULL); // 添加你自己的蜂鸣器触发事件
//}




