// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#include "../ui.h"

void ui_comp_TabPageres_create_hook(lv_obj_t * comp)
{
}

void ui_comp_List_create_hook(lv_obj_t * comp)
{
}
