// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#ifndef _UI_COMP_LIST_H
#define _UI_COMP_LIST_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT List
#define UI_COMP_LIST_LIST 0
#define UI_COMP_LIST_LISTKEYLABEL 1
#define UI_COMP_LIST_LISTINFOLABEL 2
#define UI_COMP_LIST_LISTRESTLABEL 3
#define UI_COMP_LIST_SWITCH1 4
#define UI_COMP_LIST_LISTNUMAREA 5
#define UI_COMP_LIST_BUTTON1 6
#define UI_COMP_LIST_BUTTON1_LABEL4 7
#define _UI_COMP_LIST_NUM 8
lv_obj_t * ui_List_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
