// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: artpidemo

#include "../ui.h"

// COMPONENT List

lv_obj_t * ui_List_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_List;
    cui_List = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_List, 60);
    lv_obj_set_width(cui_List, lv_pct(100));
    lv_obj_set_align(cui_List, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_List, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_List, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_List, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_List, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_List, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_listkeyLabel;
    cui_listkeyLabel = lv_label_create(cui_List);
    lv_obj_set_width(cui_listkeyLabel, 50);
    lv_obj_set_height(cui_listkeyLabel, 50);
    lv_obj_set_x(cui_listkeyLabel, 5);
    lv_obj_set_y(cui_listkeyLabel, 0);
    lv_obj_set_align(cui_listkeyLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_listkeyLabel, "key");
    lv_obj_clear_flag(cui_listkeyLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(cui_listkeyLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_listkeyLabel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_listkeyLabel, lv_color_hex(0xD5EAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_listkeyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_listkeyLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_listkeyLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_listkeyLabel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_listkeyLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_listinfoLabel;
    cui_listinfoLabel = lv_label_create(cui_List);
    lv_obj_set_width(cui_listinfoLabel, 275);
    lv_obj_set_height(cui_listinfoLabel, 50);
    lv_obj_set_x(cui_listinfoLabel, 63);
    lv_obj_set_y(cui_listinfoLabel, 0);
    lv_obj_set_align(cui_listinfoLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_listinfoLabel, "INFO");
    lv_obj_set_style_radius(cui_listinfoLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_listinfoLabel, lv_color_hex(0xD5EAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_listinfoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_listinfoLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_listinfoLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_listinfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_listinfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_listrestLabel;
    cui_listrestLabel = lv_label_create(cui_List);
    lv_obj_set_width(cui_listrestLabel, 50);
    lv_obj_set_height(cui_listrestLabel, 50);
    lv_obj_set_x(cui_listrestLabel, 347);
    lv_obj_set_y(cui_listrestLabel, 0);
    lv_obj_set_align(cui_listrestLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_listrestLabel, "");
    lv_obj_set_style_radius(cui_listrestLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_listrestLabel, lv_color_hex(0xD5EAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_listrestLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_listrestLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_listrestLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_listrestLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_listrestLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Switch1;
    cui_Switch1 = lv_switch_create(cui_List);
    lv_obj_set_width(cui_Switch1, 50);
    lv_obj_set_height(cui_Switch1, 25);
    lv_obj_set_x(cui_Switch1, 125);
    lv_obj_set_y(cui_Switch1, 0);
    lv_obj_set_align(cui_Switch1, LV_ALIGN_CENTER);

    lv_obj_t * cui_listnumArea;
    cui_listnumArea = lv_textarea_create(cui_List);
    lv_obj_set_width(cui_listnumArea, 70);
    lv_obj_set_height(cui_listnumArea, lv_pct(75));
    lv_obj_set_x(cui_listnumArea, 200);
    lv_obj_set_y(cui_listnumArea, 0);
    lv_obj_set_align(cui_listnumArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(cui_listnumArea, "num");

    lv_obj_t * cui_Button1;
    cui_Button1 = lv_btn_create(cui_List);
    lv_obj_set_width(cui_Button1, 70);
    lv_obj_set_height(cui_Button1, lv_pct(75));
    lv_obj_set_x(cui_Button1, 275);
    lv_obj_set_y(cui_Button1, 0);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Button1);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "Get");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LIST_NUM);
    children[UI_COMP_LIST_LIST] = cui_List;
    children[UI_COMP_LIST_LISTKEYLABEL] = cui_listkeyLabel;
    children[UI_COMP_LIST_LISTINFOLABEL] = cui_listinfoLabel;
    children[UI_COMP_LIST_LISTRESTLABEL] = cui_listrestLabel;
    children[UI_COMP_LIST_SWITCH1] = cui_Switch1;
    children[UI_COMP_LIST_LISTNUMAREA] = cui_listnumArea;
    children[UI_COMP_LIST_BUTTON1] = cui_Button1;
    children[UI_COMP_LIST_BUTTON1_LABEL4] = cui_Label4;
    lv_obj_add_event_cb(cui_List, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_List, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_List_create_hook(cui_List);
    return cui_List;
}

